"""Generalised KL (I-divergence): the beta = 1 member of the beta-divergence
family, with CONSTANT gradient weight.

Bregman divergence generated by phi(u) = u ln u - u, so phi''(u) = 1/u and the
gradient weight is w(u) = u phi''(u) = 1.  With the prediction in the second
slot and u = e^p, T = e^q:

    D(e^q, e^p) = e^q (q - p) - e^q + e^p,      dL/dp = e^p - e^q.

This is an important baseline rather than an afterthought.  By the criterion
this codebase uses -- an exploding gradient is recoverable by clipping, a
vanishing one is not -- generalised KL ALREADY removes squared error's fatal
tail:

    p -> -inf :  dL/dp -> -e^q      bounded and NON-ZERO (no vanishing)
    p -> +inf :  dL/dp ~   e^p      explodes, but singly, so clipping works

So the honest claim for the Spence loss is not that it is the only well-behaved
member of the family, but that it is the only one whose gradient is linear in
the log-space prediction on BOTH sides, and hence needs no clipping at all.
Generalised KL is the arm that makes that claim falsifiable.
"""

import torch

_VALUE_CLAMP = 30.0
_VALUE_MAX = 1e30
_GRAD_MAX = 1e30


def gen_kl_grad(input: torch.Tensor, target: torch.Tensor):
    """Exact gradient e^p - e^q, saturated to the float range.

    Written with expm1 so the small-error regime is exact:
    e^p - e^q = expm1(p) - expm1(q).
    """
    g = torch.expm1(input) - torch.expm1(target)
    return torch.nan_to_num(g, nan=0.0, posinf=_GRAD_MAX, neginf=-_GRAD_MAX)


class _GenKL(torch.autograd.Function):
    @staticmethod
    def forward(ctx, input, target):
        ctx.save_for_backward(input, target)
        p = input.clamp(max=_VALUE_CLAMP)
        q = target.clamp(max=_VALUE_CLAMP)
        val = torch.exp(q) * (q - p) - torch.exp(q) + torch.exp(p)
        return torch.nan_to_num(val, nan=_VALUE_MAX, posinf=_VALUE_MAX)

    @staticmethod
    def backward(ctx, grad_output):
        input, target = ctx.saved_tensors
        if ctx.needs_input_grad[1]:
            raise NotImplementedError(
                "gen_kl: gradient w.r.t. the target is not implemented -- "
                "regression targets must be detached."
            )
        return grad_output * gen_kl_grad(input, target), None


def gen_kl(input, target):
    """Elementwise generalised KL divergence ``D(exp(target), exp(input))``."""
    return _GenKL.apply(input, target)
