"""Itakura-Saito divergence between exponentials of log-space inputs.

The Bregman divergence generated by phi(u) = -ln u, with the PREDICTION in
the second argument (the slot whose population minimiser is the plain mean,
argmin_u E[D(T,u)] = E[T]; with the slots swapped one gets the harmonic mean
instead).  Writing u = e^p for the prediction and T = e^q for the target,

    D_IS(e^q, e^p) = e^{q-p} - (q - p) - 1,      dL/dp = 1 - e^{q-p}.

Tail behaviour, which is why it is in the paper as a reference point:
  * over-prediction (p -> +inf): gradient saturates at +1 -- BOUNDED, so the
    exploding tail of exp-space squared error is removed;
  * under-prediction (p -> -inf): gradient ~ -e^{q-p} -- EXPLODES.
So Itakura-Saito inverts squared error's asymmetry rather than removing it,
trading the unrecoverable failure (a gradient decayed to zero) for the
clippable one.

The divergence depends on p and q only through q - p, so it is scale
invariant: unlike ``exp_mse`` and the log-quadratic Bregman loss it is
completely insensitive to ``loss_shift``.

Same value/gradient split as the sibling losses: the VALUE is sanitised for
monitoring, the BACKWARD returns the exact closed form saturated to the float
range.  Targets must be detached.
"""

import torch

_VALUE_CLAMP = 30.0
_VALUE_MAX = 1e30
_GRAD_MAX = 1e30


def itakura_saito_grad(input: torch.Tensor, target: torch.Tensor):
    """Exact gradient ``1 - e^{q-p}``, saturated to the float range.

    Computed with expm1 so that the small-error regime |q - p| << 1 is exact
    rather than a difference of nearly-equal numbers:  1 - e^{d} = -expm1(d).
    """
    g = -torch.expm1(target - input)
    return torch.nan_to_num(g, nan=0.0, posinf=_GRAD_MAX, neginf=-_GRAD_MAX)


class _ItakuraSaito(torch.autograd.Function):
    @staticmethod
    def forward(ctx, input, target):
        ctx.save_for_backward(input, target)
        d = (target - input).clamp(max=_VALUE_CLAMP)
        # e^d - d - 1 == expm1(d) - d, exact for small |d|.
        val = torch.expm1(d) - d
        return torch.nan_to_num(val, nan=_VALUE_MAX, posinf=_VALUE_MAX)

    @staticmethod
    def backward(ctx, grad_output):
        input, target = ctx.saved_tensors
        if ctx.needs_input_grad[1]:
            raise NotImplementedError(
                "itakura_saito: gradient w.r.t. the target is not implemented "
                "-- regression targets must be detached."
            )
        return grad_output * itakura_saito_grad(input, target), None


def itakura_saito(input, target):
    """Elementwise Itakura-Saito divergence ``D_IS(exp(target), exp(input))``
    with a numerically stable exact gradient; see the module docstring."""
    return _ItakuraSaito.apply(input, target)
